#%RAML 1.0 DataType 
type: array
items:
  type: object
  properties:
    number:
      type: string
      example: A
      required: false
    status:
      type: boolean
      example: false
      required: false
    floor:
      type: integer
      example: 2
      required: false
    pending-request:
      type: array
      items:
        type: object
        properties:
          floor:
            type: integer
            example: 1
            required: false
          userId:
            type: integer
            example: 5
            required: false
          timestamp:
            type: integer
            example: 14567811
            required: false
