[
  {
    "number" : "A",
    "status" : false, 
    "floor" : 2,
    "pending-request" : [
      {
        "floor": 1,
        "userId":5,
        "timestamp": 14567811
      }
    ]
  },
  {
    "number" : "B",
    "status" : true, 
    "floor" : 1,
    "pending-request" : [
      {
        "floor": 2,
        "userId":10,
        "timestamp": 14567895
      }
    ]
  }  
]